dataset:
  target: dataset.codeformer_rs_train.CodeformerDataset
  params:
    # Path to the file list.
    file_list: ../dataset/Synthetic-v18-45k/train/train_hr.txt
    file_list_dlg: ../dataset/Synthetic-v18-45k/train/train_ref.txt
    
    out_size: 256
    crop_type: none
    use_hflip: False
    



data_loader:
  batch_size: 16
  shuffle: true
  num_workers: 4
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
