data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: configs/dataset/rs_dlg_train.yaml
    # Path to validation set configuration file.
    val_config: configs/dataset/rs_dlg_val.yaml

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/cldm.yaml
  # Path to the checkpoints or weights you want to resume. At the begining, 
  # this should be set to the initial weights created by scripts/make_stage2_init_weight.py.


  resume: magc_ckpts/ckpts_stage2/v54_step=129999-lpips=0.3981.ckpt



lightning:
  seed: 231
  
  trainer:
    accelerator: ddp
    precision: 32
    # Indices of GPUs used for training.
    gpus: [2,3]
    # Path to save logs and checkpoints.
    default_root_dir: save_dir
    # Max number of training steps (batches).
    max_steps: 500001
    # Validation frequency in terms of training steps.
    val_check_interval: 900
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.


        # # first stage
        # every_n_train_steps: 1000
        # monitor: 'val_loss'
        # save_top_k: 1
        # mode: 'min'
        # filename: "{step}-{val_loss:.4f}"

        # second stage
        every_n_train_steps: 1000
        monitor: 'lpips'
        save_top_k: 1
        mode: 'min'
        filename: "{step}-{lpips:.4f}"

